spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    change-log: "db/changelog/changelog-master.xml"

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE