spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE