spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE